config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'chatroom#home'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'online_users', to: 'users#online_users'
  resources :friend_request, only: [:create, :destroy]
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :sender, class_name: :User
  belongs_to :reciever, class_name: :User
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence:true

  scope :custom_display, -> {order(:created_at).last(20)}
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence:true, length: {minimum: 3, maximum:15}, uniqueness: true,
             uniqueness: {case_sensitive: false}
  has_many :messages
  has_many :friend_requests_as_sender, foreign_key: :sender, class_name: :FriendRequest
  has_many :friend_requests_as_reciever, foreign_key: :reciever, class_name: :FriendRequest
  has_secure_password


  def except_current_user(users)
    users.reject {|user| user.id == self.id}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController

  before_action :require_user
  def home
    @message = Message.new
    @messages = Message.custom_display
  end
end

app/controllers/friend_request_controller.rb
class FriendRequestController < ApplicationController
  def create
    @friend_request = FriendRequest.new(friend_request_params)
    if @friend_request.save
        flash[:now] = "friend request sent successfully"
        redirect_to root_path
    end
  end

  private
  def friend_request_params
    params.permit(:sender_id, :reciever_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", mod_message: message_render(message)
    end
  end
  private
  def message_params
    params.require(:message).permit(:body)
  end
  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_require, only: [:new, :create]
  def new
  end
  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      user.status = "online"
      user.save
      flash[:success] = "logged in was successful"
      redirect_to root_path
    else
      flash.now[:error] = "username or password was incorrect"
      render 'new'
    end
  end
  def destroy
    user = User.find_by(id: session[:user_id])
    session[:user_id] = nil
    user.status = "offline"
    user.save
    flash[:success] = "logged out successfully"
    redirect_to login_path
  end

  private
  def logged_in_require
    if loggedIn
      flash[:error] = "you are already logged in:) "
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signup_required, only: [:new, :create]
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "user created successfully.. now you can login:)"
      redirect_to login_path
    end
  end
  def online_users
    @online_users = User.where(status: "online")
    @online_users = current_user.except_current_user(@online_users)
    @requested_users = current_user.friend_requests_as_sender
    @user_list = []
    @requested_users.each do |user|
        @user_list.append(user.reciever.id)
    end
    if @online_users
      respond_to do |response|
        response.js {render partial: 'users/online_users'}
      end
    end
  end
  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
  def signup_required
    if loggedIn
      flash[:error] = "you are already signed up :) "
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
      
      @currentUser ||= User.find(session[:user_id]) if session[:user_id]
    end
    def loggedIn
      !!current_user
    end
    def require_user
      if !loggedIn
        flash[:error] = "you must log in first"
        redirect_to login_path
      end
    end
end

app/helpers/friend_request_helper.rb
module FriendRequestHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/views/chatroom/home.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="paper plane icon orange"></i>
  say somthing
</h4>

<div class="ui two column grid">
  <div class="four wide column">
    <div class="ui fluid raise card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu" style = "width: 100%;">
          <a class="active item online_users_header">
              <h4>Online Users</h4>
          </a>
          <div class="content">
            <div id="active_users" style = "margin-left:25px; padding-bottom:5px;">
              
            </div>
          </div>
          <a class="item">
            <h4>Friends</h4>
          </a>
          <div class="content">
            <div class="ui list" style = "margin-left:25px; padding-bottom:5px;">
              <div class="item">Apples</div>
              <div class="item">Pears</div>
              <div class="item">Oranges</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="twelve wide column">
    <div class="ui fluid raise card chatbox">
      <div class="content" id="messages">
        <div class="ui  feed" id="message-container">
          <% if @messages %>
            <%= render @messages %>
          <% else %>
            <h5>there is no messages yet..</h5>
          <% end %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body %>
              <%= f.button '<i class="bordered inverted orange send icon"></i>'.html_safe %>
              <%= link_to ('<i class="sync small alternate orange icon" id= "online_users"></i>').html_safe, online_users_path() , remote: true %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/friend_request/_result.js.erb
// $('#friend_request_button').empty();
// $('#friend_request_button').html('<i class="small orange clock  icon"></i>');

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to 'Chatroom', root_path(), class: "item" %>
<a class="item">
  Messages
</a>
<div class="right menu">
  <div class="ui dropdown item">
    Account <i class="dropdown icon"></i>
    <div class="menu">
      <% if loggedIn %>
        <%= link_to 'logout', logout_path(), class: "item", method: :delete %>
      <% else %>
        <%= link_to 'login', login_path(), class: "item" %>
      <% end %>
    </div>
  </div>
  <% if !loggedIn %>
    <div class="item">
        <%= link_to 'login', login_path(), class: "ui primary button" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imessage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div class="ui small inverted menu">
        <div class="ui container">
          <%= render 'layouts/navigation'%>
        </div>
    </div>
    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em> <%= message.user.username %> </em>: <%= message.body %>
    </div>
  </div>
</div>

app/views/users/_online_users.html.erb
<% @online_users.each do |user| %>
    <div class="ui grid">
      <div class="four wide column">
          <h5 style= "color:#fff;"><%= user.username %></h5>
      </div>
      <div class="four wide column"></div>
      <div class="four wide column"></div>
      <div class="four wide column" id="friend_request_button">
        <% if @requested_users.empty? %>
            <%= link_to ('<i class="small orange plus  icon"></i>').html_safe, friend_request_index_path(sender_id: current_user.id, reciever_id: user.id), method: :post %>
        <% else %>
              <% if @user_list.include? user.id %>
                  <i class="small orange clock  icon"></i>
              <% else %>
                  <%= link_to ('<i class="small orange plus  icon"></i>').html_safe, friend_request_index_path(sender_id: current_user.id, reciever_id: user.id), method: :post %>
              <% end %>
        <% end %>
      </div>
    </div>

<% end %>

app/views/users/_online_users.js.erb
document.getElementById('active_users').innerHTML = '<%= j render 'users/online_users.html' %>'

app/views/users/new.html.erb
<div class="ui placeholder segment">
  <div class="ui one column very relaxed stackable grid">
    <div class="column">
      <%= form_for(@user, html: {class: "ui form", role: "form"}, url: signup_path)  do |f| %>
        <div class="field">
          <%= f.label :username, "username" %>
          <div class="ui left icon input">
            <%= f.text_field :username, placeholder: "username" %>
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <%= f.label :password, "password" %>
          <div class="ui left icon input">
            <%= f.password_field :password, placeholder: "password" %>
            <i class="lock icon"></i>
          </div>
        </div>
        <%= f.button "signup", class: "ui orange submit button" %>
     <% end %>

    </div>
</div>